### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by bronze1man** [google/gopacket#123]
```
panic: runtime error: slice bounds out of range

goroutine 9 [running]:
code.google.com/p/gopacket/layers.(*TCP).SerializeTo(0xc20a10e140, 0x7fb8b8104328, 0xc20a0facf0, 0x410100, 0x0, 0x0)
        /root/xxx/src/code.google.com/p/gopacket/layers/tcp.go:101 +0x8d8
code.google.com/p/gopacket.SerializeLayers(0x7fb8b8104328, 0xc20a0facf0, 0xc209dd0100, 0xc20a0fc620, 0x2, 0x2, 0x0, 0x0)
        /root/xxx/src/code.google.com/p/gopacket/writer.go:190 +0xc1
```

**Comment by gconnell** [comment]
Any chance you could send us a way to recreate a TCP{} struct that exhibits this behavior?

**Comment by bronze1man** [comment]
just got a new one:
```
panic: cannot currently serialize IPv4 options

goroutine 9 [running]:
fastCat/fcVpn.gopacketserialize(0x7f0d4d520d60, 0xc20a2c8dc0, 0x0, 0x0, 0x0)
        /root/xxx/src/fastCat/fcVpn/iprewrite.go:87 +0x43f
fastCat/fcVpn.recomputeIpPacketChecksum(0xc20a1f8b4d, 0x34, 0x38)
        /root/xxx/src/fastCat/fcVpn/iprewrite.go:28 +0xd8
```

**Comment by bronze1man** [comment]
It turn out that the clients of my project have some data races.
Arbitrarily bytes has treated as ipv4/tcp packet to gopacket to unserialize a tcp packet,and to serialize and compute checksums to bytes.

Does gopacket need to protect against arbitrarily bytes input,(return error but not panic)?
