### ISSUE TITLE
Panic: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by r0t3n** [google/gopacket#335]
Getting this from a statically compiled binary. Works fine when dynamically compiled.

```fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7f3450161f23]

runtime stack:
runtime.throw(0x990298, 0x2a)
        /usr/lib/go-1.8/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/lib/go-1.8/src/runtime/signal_unix.go:274 +0x2db

goroutine 13 [syscall, locked to thread]:
runtime.cgocall(0x7b3420, 0xc420037910, 0x98fc19)
        /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc4200378d0 sp=0xc420037890
github.com/google/gopacket/pcap._Cfunc_pcap_compile(0x7f34400009f0, 0xc420a68390, 0x7f34400008e0, 0x1, 0x0)
        github.com/google/gopacket/pcap/_obj/_cgo_gotypes.go:230 +0x4d fp=0xc420037910 sp=0xc4200378d0
github.com/google/gopacket/pcap.(*Handle).compileBPFFilter.func4(0x7f34400009f0, 0xc420a68390, 0x7f34400008e0, 0x1, 0xffffffff)
        /root/go/src/github.com/google/gopacket/pcap/pcap.go:513 +0x116 fp=0xc420037958 sp=0xc420037910
github.com/google/gopacket/pcap.(*Handle).compileBPFFilter(0xc4211c0d20, 0xc420056120, 0x5c, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/google/gopacket/pcap/pcap.go:513 +0x1c1 fp=0xc4200379c0 sp=0xc420037958
github.com/google/gopacket/pcap.(*Handle).SetBPFFilter(0xc4211c0d20, 0xc420056120, 0x5c, 0x0, 0x0)
        /root/go/src/github.com/google/gopacket/pcap/pcap.go:555 +0x7e fp=0xc420037a20 sp=0xc4200379c0
bitbucket.org/r0t3n/nodemon/stream.(*Monitor).MonitorInterface(0xe03660, 0xc420a719b0, 0x6, 0xc420056120, 0x5c, 0x0, 0xa, 0xc420010100, 0x0, 0x0, ...)
        /root/go/src/bitbucket.org/r0t3n/nodemon/stream/stream.go:262 +0x6c7 fp=0xc420037ee8 sp=0xc420037a20
bitbucket.org/r0t3n/nodemon/nodemon.(*Nodemon).Run.func3(0xc4211f7200, 0xc42000e1e0, 0xc4212726b0, 0xc4212726c0)
        /root/go/src/bitbucket.org/r0t3n/nodemon/nodemon/nodemon.go:233 +0x119 fp=0xc420037fc0 sp=0xc420037ee8
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420037fc8 sp=0xc420037fc0
created by bitbucket.org/r0t3n/nodemon/nodemon.(*Nodemon).Run
        /root/go/src/bitbucket.org/r0t3n/nodemon/nodemon/nodemon.go:236 +0x1bdc

goroutine 1 [chan receive]:
github.com/kardianos/service.(*systemd).Run.func1()
        /root/go/src/github.com/kardianos/service/service_systemd_linux.go:138 +0xe7
github.com/kardianos/service.(*systemd).Run(0xc42117d5a0, 0x996770, 0xc4200576e0)
        /root/go/src/github.com/kardianos/service/service_systemd_linux.go:139 +0xc0
main.main()
        /root/go/src/bitbucket.org/r0t3n/nodemon/main.go:50 +0x2a5

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go-1.8/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /usr/lib/go-1.8/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/lib/go-1.8/src/os/signal/signal_unix.go:28 +0x41

goroutine 7 [chan receive]:
main.main.func1(0xc4200576e0)
        /root/go/src/bitbucket.org/r0t3n/nodemon/main.go:36 +0x57
created by main.main
        /root/go/src/bitbucket.org/r0t3n/nodemon/main.go:41 +0x27c

goroutine 8 [chan receive]:
database/sql.(*DB).connectionOpener(0xc421274640)
        /usr/lib/go-1.8/src/database/sql/sql.go:837 +0x4a
created by database/sql.Open
        /usr/lib/go-1.8/src/database/sql/sql.go:582 +0x212

goroutine 12 [chan receive]:
bitbucket.org/r0t3n/nodemon/stream.(*Monitor).MonitorInterface(0xe03660, 0xc420a718d0, 0xa, 0xc420056120, 0x5c, 0x0, 0xa, 0x10100, 0x0, 0x0, ...)
        /root/go/src/bitbucket.org/r0t3n/nodemon/stream/stream.go:306 +0xe07
bitbucket.org/r0t3n/nodemon/nodemon.(*Nodemon).Run.func3(0xc4211f7180, 0xc42000e1e0, 0xc4212726b0, 0xc4212726c0)
        /root/go/src/bitbucket.org/r0t3n/nodemon/nodemon/nodemon.go:233 +0x119
created by bitbucket.org/r0t3n/nodemon/nodemon.(*Nodemon).Run
        /root/go/src/bitbucket.org/r0t3n/nodemon/nodemon/nodemon.go:236 +0x1bdc

goroutine 10 [chan receive]:
bitbucket.org/r0t3n/nodemon/nodemon.(*Nodemon).Run(0xc42004d770, 0x0, 0x0)
        /root/go/src/bitbucket.org/r0t3n/nodemon/nodemon/nodemon.go:249 +0x57c
created by bitbucket.org/r0t3n/nodemon/nodemon.(*Nodemon).Start
        /root/go/src/bitbucket.org/r0t3n/nodemon/nodemon/nodemon.go:101 +0x6fe

goroutine 11 [select, locked to thread]:
runtime.gopark(0x996d20, 0x0, 0x970300, 0x6, 0x18, 0x2)
        /usr/lib/go-1.8/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc420035f50, 0x0, 0x18)
        /usr/lib/go-1.8/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc420035f50)
        /usr/lib/go-1.8/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /usr/lib/go-1.8/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

goroutine 15 [runnable, locked to thread]:
github.com/google/gopacket/pcap._Cfunc_pcap_next_ex(0x7f34440009f0, 0xc4211c0950, 0xc4211c0958, 0x0)
        github.com/google/gopacket/pcap/_obj/_cgo_gotypes.go:435 +0x4d
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked.func1(0x7f34440009f0, 0xc4211c0950, 0xc4211c0958, 0x1)
        /root/go/src/github.com/google/gopacket/pcap/pcap.go:357 +0x198
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked(0xc4211c0910, 0xc420023eb0, 0x0, 0x0)
        /root/go/src/github.com/google/gopacket/pcap/pcap.go:357 +0x59
github.com/google/gopacket/pcap.(*Handle).ReadPacketData(0xc4211c0910, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/google/gopacket/pcap/pcap.go:307 +0x77
github.com/google/gopacket.(*PacketSource).NextPacket(0xc421280a80, 0x996b00, 0xc420057a40, 0x0, 0xc420a71cd8)
        /root/go/src/github.com/google/gopacket/packet.go:795 +0x48
github.com/google/gopacket.(*PacketSource).packetsToChannel(0xc421280a80)
        /root/go/src/github.com/google/gopacket/packet.go:812 +0x5d
created by github.com/google/gopacket.(*PacketSource).Packets
        /root/go/src/github.com/google/gopacket/packet.go:835 +0x94

**Comment by r0t3n** [comment]
To add to this, I worked around this specific issue by compiling the BPF outside any goroutine and setting bpf instructions on the pcap handles.

I have mutex locks placed around the bpf code which still did not prevent the error, the first filter applied successfully and packet capturing started, any other calls in other goroutines to set a filter on another handle failed. I tried with libpcap 1.7.4 and also 1.8.1 compiled from source which i believe is now thread safe for pcap_compile.

I now have another issue where Close()'ing a pcap handle hangs. Again, this only happens when libpcap is statically compiled into the binary, dynamic linking works 100% as it should.

As all works as should with a dynamically linked libpcap, it seems there is some issues with gopacket using a statically compiled libpcap.
