### ISSUE TITLE
pcap: pcap_wait panics when more than 1024 file descriptors are open

### ISSUE THREAD

**Issue by Kegian** [google/gopacket#763]
I encountered a problem when using pcap in an app that opens more than 1024 file descriptors.  Attempting to do this results in a sigsegv.

`system`: LMDE 3 Cindy
`go version`: go1.13.1 linux/amd64

Here is the minimal reproduction:
```
$ ulimit -S -n 2048
$ go run main.go
```
**main.go**
```go
package main

import (
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/google/gopacket"
	"github.com/google/gopacket/pcap"
)

const LinkName = "eth0"

func main() {
	tmp := filepath.Join(os.TempDir(), "pcap-test")
	defer os.Remove(tmp)

	for i := 0; i < 1024; i++ {
		f, err := os.OpenFile(tmp, os.O_RDONLY|os.O_CREATE, 0600)
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
	}

	h, err := pcap.OpenLive(LinkName, 1024, false, time.Second)
	if err != nil {
		log.Fatal(err)
	}

	packetSource := gopacket.NewPacketSource(h, h.LinkType())
	for packet := range packetSource.Packets() {
		log.Println(packet)
	}
}

```
Output:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5254d4]

runtime stack:
runtime.throw(0x5ab94d, 0x2a)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 6 [syscall]:
runtime.cgocall(0x5254b0, 0xc000052568, 0xc000052560)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000052538 sp=0xc000052500 pc=0x40620b
github.com/google/gopacket/pcap._Cfunc_pcap_wait(0x2198660, 0xf41dc, 0x0)
	_cgo_gotypes.go:871 +0x4d fp=0xc000052568 sp=0xc000052538 pc=0x5236ed
github.com/google/gopacket/pcap.(*Handle).waitForPacket.func1(0xc00016cd20, 0xf41dc, 0x0)
	/usr/lib/golang/src/github.com/google/gopacket/pcap/pcap_unix.go:694 +0x68 fp=0xc0000525a8 sp=0xc000052568 pc=0x524428
github.com/google/gopacket/pcap.(*Handle).waitForPacket(0xc00016cd20)
	/usr/lib/golang/src/github.com/google/gopacket/pcap/pcap_unix.go:694 +0x7a fp=0xc0000525d0 sp=0xc0000525a8 pc=0x523e1a
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked(0xc00016cd20, 0xc000052678, 0x0, 0x0)
	/usr/lib/golang/src/github.com/google/gopacket/pcap/pcap.go:340 +0x3e fp=0xc0000525f8 sp=0xc0000525d0 pc=0x522e3e
github.com/google/gopacket/pcap.(*Handle).ReadPacketData(0xc00016cd20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/github.com/google/gopacket/pcap/pcap.go:252 +0x8b fp=0xc000052658 sp=0xc0000525f8 pc=0x522c6b
github.com/google/gopacket.(*PacketSource).NextPacket(0xc00009cab0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/github.com/google/gopacket/packet.go:801 +0x48 fp=0xc000052740 sp=0xc000052658 pc=0x4b9a38
github.com/google/gopacket.(*PacketSource).packetsToChannel(0xc00009cab0)
	/usr/lib/golang/src/github.com/google/gopacket/packet.go:818 +0x83 fp=0xc0000527d8 sp=0xc000052740 pc=0x4b9cb3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000527e0 sp=0xc0000527d8 pc=0x458d41
created by github.com/google/gopacket.(*PacketSource).Packets
	/usr/lib/golang/src/github.com/google/gopacket/packet.go:861 +0x8d

goroutine 1 [chan receive]:
main.main()
	/usr/lib/golang/src/pcap/main.go:33 +0x395
exit status 2
```

This happens due using `select` function which require `fd_set`([pcap_unix.go:146](https://github.com/google/gopacket/blob/acf5713f69a6d7d46793de01046a2e72f6c2d84f/pcap/pcap_unix.go#L146)) as an argument. 
According to [man 2 select](http://man7.org/linux/man-pages/man2/select.2.html): 
> The Linux kernel imposes no fixed limit, but the glibc implementation makes fd_set a fixed size type, with FD_SETSIZE defined as 1024, and the FD_*() macros operating according to that limit.

So passing fds greater than 1023 results in UB. Using `poll` instead of `select` fixed this problem in my case.

**Comment by Ice3man543** [comment]
@Kegian do you have a fork of the repo somewhere with this problem fixed? I'm experiencing the same issue with gopacket latest version.

**Comment by Mzack9999** [comment]
This should be fixed in this fork https://github.com/Mzack9999/gopacket
