### ISSUE TITLE
panic slice bounds out of range

### ISSUE THREAD

**Issue by jank1369** [google/gopacket#881]
gopacket/layers/dns.go.  632 , need boundary check

// decode decodes the resource record, returning the total length of the record.
func (rr *DNSResourceRecord) decode(data []byte, offset int, df gopacket.DecodeFeedback, buffer *[]byte) (int, error) {
	name, endq, err := decodeName(data, offset, buffer, 1)
	if err != nil {
		return 0, err
	}

	rr.Name = name
	rr.Type = DNSType(binary.BigEndian.Uint16(data[endq : endq+2]))
	rr.Class = DNSClass(binary.BigEndian.Uint16(data[endq+2 : endq+4]))
	rr.TTL = binary.BigEndian.Uint32(data[endq+4 : endq+8])
	rr.DataLength = binary.BigEndian.Uint16(data[endq+8 : endq+10])
	end := endq + 10 + int(rr.DataLength)
	if end > len(data) {
		return 0, errDecodeRecordLength
	}
	rr.Data = data[endq+10 : end]

	if err = rr.decodeRData(data, endq+10, buffer); err != nil {
		return 0, err
	}

	return endq + 10 + int(rr.DataLength), nil
}

**Comment by icamys** [comment]
Got the same issue today. Here's the code that reproduces the issue:

```golang
package main

import (
	"bytes"

	"github.com/google/gopacket"
	"github.com/google/gopacket/layers"
	"github.com/google/gopacket/pcapgo"
)

func main() {
	var ip4 layers.IPv4
	var udp layers.UDP
	var dns layers.DNS

	// A malformed DNS packet
	var data = []byte{
		212,195,178,161,2,0,4,0,0,0,0,0,0,0,0,0,0,0,1,0,101,0,0,0,108,188,26,97,23,111,
		0,0,42,0,0,0,42,0,0,0,69,0,0,42,56,83,64,0,59,17,211,102,167,71,102,181,161,35,132,233,
		207,47,0,53,0,22,210,224,56,101,20,46,201,63,218,159,57,0,0,0,0,0,109,188,26,97,90,118,0,0,
		70,0,0,0,70,0,0,0,69,192,0,70,46,90,0,0,64,1,23,148,161,35,132,233,167,71,102,181,3,3,
		49,46,0,0,0,0,69,0,0,42,56,83,64,0,59,17,211,102,167,71,102,181,161,35,132,233,207,47,0,53,
		0,22,210,224,56,101,20,46,201,63,218,159,57,0,0,0,0,0,
	}

	reader := bytes.NewReader(data)
	pcapReader, _ := pcapgo.NewReader(reader)
	parser := gopacket.NewDecodingLayerParser(layers.LayerTypeIPv4, &ip4, &udp, &dns)
	decodedLayers := make([]gopacket.LayerType, 0, 10)
	packetData, _, _ := pcapReader.ReadPacketData()
	err := parser.DecodeLayers(packetData, &decodedLayers)
	if err != nil {
		println(err.Error())
	}
}
```

I suppose that increasing the minimum required length for the `data` variable  [here](https://github.com/google/gopacket/blob/master/layers/dns.go#L307) up to 17 will fix the issue.

17 = 12 (DNS name) + 2 (DNS type) + 4 (DNS class)

Another workaround would be to check the `data` length before identifying the type and class in the [decode function](https://github.com/google/gopacket/blob/3eaba08943250fd212520e5cff00ed808b8fc60a/layers/dns.go#L636) and if it's too short, return `errDNSPacketTooShort`. 

Any thoughts?

**Comment by AndreLaxe** [comment]
Hello, I think this commit https://github.com/google/gopacket/commit/65a1dfb3db2ad85763f26417f8699486bc253369 would be helpful.

**Comment by git6111** [comment]
runtime error: slice bounds out of range [:83] with capacity 82
goroutine 22 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x6b
github.com/google/gopacket.(*packet).recoverDecodeError(0xc0002a62c0)
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/packet.go:199 +0xc5
panic({0x5e2980?, 0xc000384000?})
	/usr/local/go/src/runtime/panic.go:920 +0x290
github.com/google/gopacket/layers.(*DNSResourceRecord).decode(0xc00053c1a0, {0xc00016f4ae, 0x52, 0x52}, 0x49, {0x7ff4c00b5008, 0xc0002a62c0}, 0xc000150168)
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/dns.go:715 +0x653
github.com/google/gopacket/layers.(*DNS).DecodeFromBytes(0xc0001500c0, {0xc00016f4ae, 0x52, 0x52}, {0x7ff4c00b5008, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/dns.go:358 +0x9f8
github.com/google/gopacket/layers.decodeDNS({0xc00016f4ae, 0x52, 0x52}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/dns.go:294 +0x108
github.com/google/gopacket.DecodeFunc.Decode(0x612140, {0xc00016f4ae, 0x52, 0x52}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/decode.go:87 +0x5c
github.com/google/gopacket.LayerType.Decode(0x6b, {0xc00016f4ae, 0x52, 0x52}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layertype.go:95 +0x13e
github.com/google/gopacket.(*eagerPacket).NextDecoder(0xc0002a62c0, {0x61d898, 0x726cd8})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/packet.go:449 +0xdc
github.com/google/gopacket/layers.decodeUDP({0xc00016f4a6, 0x5a, 0x5a}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/udp.go:120 +0x1f5
github.com/google/gopacket.DecodeFunc.Decode(0x6124c8, {0xc00016f4a6, 0x5a, 0x5a}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/decode.go:87 +0x5c
github.com/google/gopacket.LayerType.Decode(0x2d, {0xc00016f4a6, 0x5a, 0x5a}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layertype.go:95 +0x13e
github.com/google/gopacket.(*eagerPacket).NextDecoder(0xc0002a62c0, {0x61d898, 0x726ae8})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/packet.go:449 +0xdc
github.com/google/gopacket/layers.decodeIPv4({0xc00016f492, 0x6e, 0x6e}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/ip4.go:296 +0x1df
github.com/google/gopacket.DecodeFunc.Decode(0x612358, {0xc00016f492, 0x6e, 0x6e}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/decode.go:87 +0x5c
github.com/google/gopacket.LayerType.Decode(0x14, {0xc00016f492, 0x6e, 0x6e}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layertype.go:95 +0x13e
github.com/google/gopacket.(*eagerPacket).NextDecoder(0xc0002a62c0, {0x61d898, 0x726a20})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/packet.go:449 +0xdc
github.com/google/gopacket/layers.decodingLayerDecoder({0x61ff50, 0xc000175e40}, {0xc00016f48e, 0x72, 0x72}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/base.go:48 +0x1d5
github.com/google/gopacket/layers.decodeDot1Q({0xc00016f48e, 0x72, 0x72}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/dot1q.go:54 +0xca
github.com/google/gopacket.DecodeFunc.Decode(0x612298, {0xc00016f48e, 0x72, 0x72}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/decode.go:87 +0x5c
github.com/google/gopacket/layers.EthernetType.Decode(0x8100, {0xc00016f48e, 0x72, 0x72}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/enums_generated.go:68 +0x82
github.com/google/gopacket.(*eagerPacket).NextDecoder(0xc0002a62c0, {0x61db58, 0xc000281794})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/packet.go:449 +0xdc
github.com/google/gopacket/layers.decodeEthernet({0xc00016f480, 0x80, 0x80}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/ethernet.go:122 +0x1d9
github.com/google/gopacket.DecodeFunc.Decode(0x6122c8, {0xc00016f480, 0x80, 0x80}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/decode.go:87 +0x5c
github.com/google/gopacket.LayerType.Decode(0x11, {0xc00016f480, 0x80, 0x80}, {0x620fa0, 0xc0002a62c0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layertype.go:95 +0x13e
github.com/google/gopacket.(*eagerPacket).initialDecode(0xc0002a62c0, {0x61d898, 0x726a08})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/packet.go:453 +0xe5
github.com/google/gopacket.NewPacket({0xc00016f480, 0x80, 0x80}, {0x61d898, 0x726a08}, {0x0, 0x0, 0x0, 0x0})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/packet.go:682 +0x405
github.com/google/gopacket/layers.decodeRawPacketFlowRecord(0xc0000b73c0)
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/sflow.go:1074 +0x7e5
github.com/google/gopacket/layers.decodeFlowSample(0xc0004073c0, 0x1)
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/sflow.go:542 +0x1a1d
github.com/google/gopacket/layers.(*SFlowDatagram).DecodeFromBytes(0xc0002850e0, {0xc0002a42e8, 0xfc, 0xfc}, {0x7ff4c00b5008, 0xc0002a6160})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/sflow.go:331 +0xdd2
github.com/google/gopacket/layers.decodeSFlow({0xc0002a4200, 0x1e4, 0x1e4}, {0x620fa0, 0xc0002a6160})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layers/sflow.go:137 +0x10c
github.com/google/gopacket.DecodeFunc.Decode(0x612498, {0xc0002a4200, 0x1e4, 0x1e4}, {0x620fa0, 0xc0002a6160})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/decode.go:87 +0x5c
github.com/google/gopacket.LayerType.Decode(0x72, {0xc0002a4200, 0x1e4, 0x1e4}, {0x620fa0, 0xc0002a6160})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/layertype.go:95 +0x13e
github.com/google/gopacket.(*eagerPacket).initialDecode(0xc0002a6160, {0x61d898, 0x726d10})
	/home/usergo/go/pkg/mod/github.com/google/gopacket@v1.1.19/packet.go:453 +0xe5
github.com/google/gopacket.NewPacket({0xc0002a4200, 0x1e4, 0x1e4}, {0x61d898, 0x726d10}, {0x0, 0x1, 0x0, 0x0})


func (rr *DNSResourceRecord) decode(data []byte, offset int, df gopacket.DecodeFeedback, buffer *[]byte) (int, error) 

offset=73
data
[]uint8 len: 82, cap: 82, [240,231,133,128,0,1,0,1,0,0,0,1,34,104,100,112,45,104,97,100,111,111,112,45,100,97,116,97,110,111,100,101,45,110,111,100,101,109,97,110,97,103,101,114,45,49,49,5,97,100,109,105,110,7,115,101,114,118,105,99,101,6,99,111,...+18 mor...
string(): "\xf0煀\x00\x01\x00\x01\x00\x00\x00\x01\"hdp-hadoop-datanode-nodemanager-11\x05admin\aservice\x06consul\x00\x00\x01\x00\x01\xc0\f\x00\x01\x00\x01\x00\x00\x00"
[0]: 240 = 0xf0
[1]: 231 = 0xe7
[2]: 133 = 0x85
[3]: 128 = 0x80
[4]: 0 = 0x0
[5]: 1 = 0x1
[6]: 0 = 0x0
[7]: 1 = 0x1
[8]: 0 = 0x0
[9]: 0 = 0x0
[10]: 0 = 0x0
[11]: 1 = 0x1
[12]: 34 = 0x22
[13]: 104 = 0x68
[14]: 100 = 0x64
[15]: 112 = 0x70
[16]: 45 = 0x2d
[17]: 104 = 0x68
[18]: 97 = 0x61
[19]: 100 = 0x64
[20]: 111 = 0x6f
[21]: 111 = 0x6f
[22]: 112 = 0x70
[23]: 45 = 0x2d
[24]: 100 = 0x64
[25]: 97 = 0x61
[26]: 116 = 0x74
[27]: 97 = 0x61
[28]: 110 = 0x6e
[29]: 111 = 0x6f
[30]: 100 = 0x64
[31]: 101 = 0x65
[32]: 45 = 0x2d
[33]: 110 = 0x6e
[34]: 111 = 0x6f
[35]: 100 = 0x64
[36]: 101 = 0x65
[37]: 109 = 0x6d
[38]: 97 = 0x61
[39]: 110 = 0x6e
[40]: 97 = 0x61
[41]: 103 = 0x67
[42]: 101 = 0x65
[43]: 114 = 0x72
[44]: 45 = 0x2d
[45]: 49 = 0x31
[46]: 49 = 0x31
[47]: 5 = 0x5
[48]: 97 = 0x61
[49]: 100 = 0x64
[50]: 109 = 0x6d
[51]: 105 = 0x69
[52]: 110 = 0x6e
[53]: 7 = 0x7
[54]: 115 = 0x73
[55]: 101 = 0x65
[56]: 114 = 0x72
[57]: 118 = 0x76
[58]: 105 = 0x69
[59]: 99 = 0x63
[60]: 101 = 0x65
[61]: 6 = 0x6
[62]: 99 = 0x63
[63]: 111 = 0x6f
[64]: 110 = 0x6e
[65]: 115 = 0x73
[66]: 117 = 0x75
[67]: 108 = 0x6c
[68]: 0 = 0x0
[69]: 0 = 0x0
[70]: 1 = 0x1
[71]: 0 = 0x0
[72]: 1 = 0x1
[73]: 192 = 0xc0
[74]: 12 = 0xc
[75]: 0 = 0x0
[76]: 1 = 0x1
[77]: 0 = 0x0
[78]: 1 = 0x1
[79]: 0 = 0x0
[80]: 0 = 0x0
[81]: 0 = 0x0

buffer
*[]uint8 len: 56, cap: 96, [46,104,100,112,45,104,97,100,111,111,112,45,100,97,116,97,110,111,100,101,45,110,111,100,101,109,97,110,97,103,101,114,45,49,49,46,97,100,109,105,110,46,115,101,114,118,105,99,101,46,99,111,110,115,117,108]
[]uint8 len: 56, cap: 96, [46,104,100,112,45,104,97,100,111,111,112,45,100,97,116,97,110,111,100,101,45,110,111,100,101,109,97,110,97,103,101,114,45,49,49,46,97,100,109,105,110,46,115,101,114,118,105,99,101,46,99,111,110,115,117,108]
string(): ".hdp-hadoop-datanode-nodemanager-11.admin.service.consul"
[0]: 46 = 0x2e
[1]: 104 = 0x68
[2]: 100 = 0x64
[3]: 112 = 0x70
[4]: 45 = 0x2d
[5]: 104 = 0x68
[6]: 97 = 0x61
[7]: 100 = 0x64
[8]: 111 = 0x6f
[9]: 111 = 0x6f
[10]: 112 = 0x70
[11]: 45 = 0x2d
[12]: 100 = 0x64
[13]: 97 = 0x61
[14]: 116 = 0x74
[15]: 97 = 0x61
[16]: 110 = 0x6e
[17]: 111 = 0x6f
[18]: 100 = 0x64
[19]: 101 = 0x65
[20]: 45 = 0x2d
[21]: 110 = 0x6e
[22]: 111 = 0x6f
[23]: 100 = 0x64
[24]: 101 = 0x65
[25]: 109 = 0x6d
[26]: 97 = 0x61
[27]: 110 = 0x6e
[28]: 97 = 0x61
[29]: 103 = 0x67
[30]: 101 = 0x65
[31]: 114 = 0x72
[32]: 45 = 0x2d
[33]: 49 = 0x31
[34]: 49 = 0x31
[35]: 46 = 0x2e
[36]: 97 = 0x61
[37]: 100 = 0x64
[38]: 109 = 0x6d
[39]: 105 = 0x69
[40]: 110 = 0x6e
[41]: 46 = 0x2e
[42]: 115 = 0x73
[43]: 101 = 0x65
[44]: 114 = 0x72
[45]: 118 = 0x76
[46]: 105 = 0x69
[47]: 99 = 0x63
[48]: 101 = 0x65
[49]: 46 = 0x2e
[50]: 99 = 0x63
[51]: 111 = 0x6f
[52]: 110 = 0x6e
[53]: 115 = 0x73
[54]: 117 = 0x75
[55]: 108 = 0x6c
