### ISSUE TITLE
panic on linux

### ISSUE THREAD

**Issue by gardc** [google/gopacket#944]
Hi. I've had no problem with gopacket on Windows and Mac, but on my Ubuntu 20.04 VM I get a nasty panic. Here's the error log in case anyone can make anything of it:

```
signal 11 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime: unexpected return pc for runtime.sigtramp called from 0x7f7b5cef97ba
stack: frame={sp:0xc0003bbee0, fp:0xc0003bbf30} stack=[0xc0003b3dd8,0xc0003bc1d8)
0x000000c0003bbde0:  0x000000c0003bbe18  0x000000c0003bbe40 
0x000000c0003bbdf0:  0x663b5d5b3d736c65  0x722072617628726f 
0x000000c0003bbe00:  0x656c2e736968743d  0x303d692c736c6576 
0x000000c0003bbe10:  0x6e656c2e723d612c  0x000000c000066000 
0x000000c0003bbe20:  0x0000000000000000  0x0000000000008000 
0x000000c0003bbe30:  0x000000c0003bbea8  0x0000000000450345 <runtime.sigtrampgo+0x0000000000000145> 
0x000000c0003bbe40:  0x000000c00000000b  0x000000c00004a800 
0x000000c0003bbe50:  0x000000c0003bbe68  0x61747369642c6469 
0x000000c0003bbe60:  0x69642e6f3a65636e  0x0000000000000000 
0x000000c0003bbe70:  0x0000000000000000  0x0000000000000000 
0x000000c0003bbe80:  0x0000000000000000  0x0000000000000000 
0x000000c0003bbe90:  0x000000c000210b60  0x000000c0003bc170 
0x000000c0003bbea0:  0x000000c0003bc040  0x000000c0003bbed0 
0x000000c0003bbeb0:  0x000000000046da8e <runtime.sigtrampgo+0x000000000000002e>  0x6974636e0000000b 
0x000000c0003bbec0:  0x000000c0003bc170  0x000000c0003bc040 
0x000000c0003bbed0:  0x000000c0003bbf20  0x000000000046cf3d <runtime.sigtramp+0x000000000000003d> 
0x000000c0003bbee0: <0x000000000000000b  0x000000c0003bc170 
0x000000c0003bbef0:  0x000000c0003bc040  0x000000c0003bc068 
0x000000c0003bbf00:  0x000000c0003bbf50  0x0000000000000005 
0x000000c0003bbf10:  0xffffffffffffffff  0x0000000000000000 
0x000000c0003bbf20:  0x00007f7b5d27b0a0 !0x00007f7b5cef97ba 
0x000000c0003bbf30: >0x000000c0003bc040  0x00007f7b5d27b000 
0x000000c0003bbf40:  0x000000c0003bc170  0x0000000b00697274 
0x000000c0003bbf50:  0x0000000000000030  0x78697274614d646e 
0x000000c0003bbf60:  0x3d65737265766e49  0x692c64412077656e 
0x000000c0003bbf70:  0x206e72757465727d  0x6b7b5b2c6e287369 
0x000000c0003bbf80:  0x79706f63223a7965  0x3a65756c61762c22 
0x000000c0003bbf90:  0x6e6f6974636e7566  0x757465727b296528 
0x000000c0003bbfa0:  0x6f5a286f4b206e72  0x6f746f72702e6e28 
0x000000c0003bbfb0:  0x63222c2965707974  0x6968742c2279706f 
0x000000c0003bbfc0:  0x286c6c61632e2973  0x2c29652c73696874 
0x000000c0003bbfd0:  0x6e69622e73696874  0x2e653d65646f4d64 
0x000000c0003bbfe0:  0x65646f4d646e6962  0x69622e736968742c 
0x000000c0003bbff0:  0x78697274614d646e  0x2d7c7063ef521400 
0x000000c0003bc000:  0x000000c0003bd000  0x00000000005838a0 <github.com/google/gopacket.(*PacketSource).Packets.func1+0x0000000000000000> 
0x000000c0003bc010:  0x000000c0003bc638  0x000000c0003bc6c8 
0x000000c0003bc020:  0x0000000000000000  0x000000c000210b60 
runtime.throw({0xa5c394?, 0xc00004a000?})
	/usr/local/go/src/runtime/panic.go:992 +0x71
runtime.sigNotOnStack(0xb)
	/usr/local/go/src/runtime/signal_unix.go:1002 +0x65
runtime.adjustSignalStack(0xb, 0xc00004a800, 0xc0003bbe68)
	/usr/local/go/src/runtime/signal_unix.go:577 +0x290
runtime.sigtrampgo(0xb, 0xc0003bc170, 0xc0003bc040)
	/usr/local/go/src/runtime/signal_unix.go:467 +0x145
runtime.sigtrampgo(0xb, 0xc0003bc170, 0xc0003bc040)
	<autogenerated>:1 +0x2e
runtime: unexpected return pc for runtime.sigtramp called from 0x7f7b5cef97ba
stack: frame={sp:0xc0003bbee0, fp:0xc0003bbf30} stack=[0xc0003b3dd8,0xc0003bc1d8)
0x000000c0003bbde0:  0x000000c0003bbe18  0x000000c0003bbe40 
0x000000c0003bbdf0:  0x663b5d5b3d736c65  0x722072617628726f 
0x000000c0003bbe00:  0x656c2e736968743d  0x303d692c736c6576 
0x000000c0003bbe10:  0x6e656c2e723d612c  0x000000c000066000 
0x000000c0003bbe20:  0x0000000000000000  0x0000000000008000 
0x000000c0003bbe30:  0x000000c0003bbea8  0x0000000000450345 <runtime.sigtrampgo+0x0000000000000145> 
0x000000c0003bbe40:  0x000000c00000000b  0x000000c00004a800 
0x000000c0003bbe50:  0x000000c0003bbe68  0x61747369642c6469 
0x000000c0003bbe60:  0x69642e6f3a65636e  0x0000000000000000 
0x000000c0003bbe70:  0x0000000000000000  0x0000000000000000 
0x000000c0003bbe80:  0x0000000000000000  0x0000000000000000 
0x000000c0003bbe90:  0x000000c000210b60  0x000000c0003bc170 
0x000000c0003bbea0:  0x000000c0003bc040  0x000000c0003bbed0 
0x000000c0003bbeb0:  0x000000000046da8e <runtime.sigtrampgo+0x000000000000002e>  0x6974636e0000000b 
0x000000c0003bbec0:  0x000000c0003bc170  0x000000c0003bc040 
0x000000c0003bbed0:  0x000000c0003bbf20  0x000000000046cf3d <runtime.sigtramp+0x000000000000003d> 
0x000000c0003bbee0: <0x000000000000000b  0x000000c0003bc170 
0x000000c0003bbef0:  0x000000c0003bc040  0x000000c0003bc068 
0x000000c0003bbf00:  0x000000c0003bbf50  0x0000000000000005 
0x000000c0003bbf10:  0xffffffffffffffff  0x0000000000000000 
0x000000c0003bbf20:  0x00007f7b5d27b0a0 !0x00007f7b5cef97ba 
0x000000c0003bbf30: >0x000000c0003bc040  0x00007f7b5d27b000 
0x000000c0003bbf40:  0x000000c0003bc170  0x0000000b00697274 
0x000000c0003bbf50:  0x0000000000000030  0x78697274614d646e 
0x000000c0003bbf60:  0x3d65737265766e49  0x692c64412077656e 
0x000000c0003bbf70:  0x206e72757465727d  0x6b7b5b2c6e287369 
0x000000c0003bbf80:  0x79706f63223a7965  0x3a65756c61762c22 
0x000000c0003bbf90:  0x6e6f6974636e7566  0x757465727b296528 
0x000000c0003bbfa0:  0x6f5a286f4b206e72  0x6f746f72702e6e28 
0x000000c0003bbfb0:  0x63222c2965707974  0x6968742c2279706f 
0x000000c0003bbfc0:  0x286c6c61632e2973  0x2c29652c73696874 
0x000000c0003bbfd0:  0x6e69622e73696874  0x2e653d65646f4d64 
0x000000c0003bbfe0:  0x65646f4d646e6962  0x69622e736968742c 
0x000000c0003bbff0:  0x78697274614d646e  0x2d7c7063ef521400 
0x000000c0003bc000:  0x000000c0003bd000  0x00000000005838a0 <github.com/google/gopacket.(*PacketSource).Packets.func1+0x0000000000000000> 
0x000000c0003bc010:  0x000000c0003bc638  0x000000c0003bc6c8 
0x000000c0003bc020:  0x0000000000000000  0x000000c000210b60 
runtime.sigtramp()
	/usr/local/go/src/runtime/sys_linux_amd64.s:361 +0x3d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000058fe8 sp=0xc000058fe0 pc=0x46b321

goroutine 1 [syscall]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux._Cfunc_gtk_main()
	_cgo_gotypes.go:961 +0x45
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Window).Run(0xc0000e15e0)
	/home/dev/dev/wails/v2/internal/frontend/desktop/linux/window.go:781 +0x8c
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).Run(0xc0000e1570, {0x160b178?, 0xc0001e8750?})
	/home/dev/dev/wails/v2/internal/frontend/desktop/linux/frontend.go:130 +0xb8
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run(0xc0000acc80, {0x160b178?, 0xc0001e8750})
	/home/dev/dev/wails/v2/internal/frontend/devserver/devserver.go:140 +0x629
github.com/wailsapp/wails/v2/internal/appng.(*App).Run(0xc00007c4b0)
	/home/dev/dev/wails/v2/internal/appng/app_dev.go:47 +0x31
github.com/wailsapp/wails/v2.Run(0xc0000021a0?)
	/home/dev/dev/wails/v2/wails.go:24 +0x33
main.main()
	/home/dev/dev/project-project-wails/main.go:26 +0x38f

goroutine 6 [chan receive]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startMessageProcessor(0x0?)
	/home/dev/dev/wails/v2/internal/frontend/desktop/linux/frontend.go:111 +0x59
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
	/home/dev/dev/wails/v2/internal/frontend/desktop/linux/frontend.go:96 +0x385

goroutine 7 [chan receive]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startRequestProcessor(0x0?)
	/home/dev/dev/wails/v2/internal/frontend/desktop/linux/frontend.go:287 +0x5a
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
	/home/dev/dev/wails/v2/internal/frontend/desktop/linux/frontend.go:97 +0x3c5

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x7f7b2dd39718, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0002bc000?, 0x46f40a?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc0002bc000)
	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc0002bc000)
	/usr/local/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc00029a030)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc00029a030)
	/usr/local/go/src/net/tcpsock.go:288 +0x3d
github.com/valyala/fasthttp.acceptConn(0xc0000a3440, {0x160ad40, 0xc00029a030}, 0xc000054ed0)
	/home/dev/go/pkg/mod/github.com/valyala/fasthttp@v1.28.0/server.go:1825 +0x62
github.com/valyala/fasthttp.(*Server).Serve(0xc0000a3440, {0x160ad40?, 0xc00029a030})
	/home/dev/go/pkg/mod/github.com/valyala/fasthttp@v1.28.0/server.go:1740 +0x4ca
github.com/gofiber/fiber/v2.(*App).Listen(0xc0002104e0, {0xa3e7da?, 0x0?})
	/home/dev/go/pkg/mod/github.com/gofiber/fiber/v2@v2.17.0/app.go:664 +0xbd
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run.func4(0x0?, 0x0?)
	/home/dev/dev/wails/v2/internal/frontend/devserver/devserver.go:122 +0x37
created by github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run
	/home/dev/dev/wails/v2/internal/frontend/devserver/devserver.go:121 +0x565

goroutine 20 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/go/src/runtime/time.go:194 +0x12e
github.com/valyala/fasthttp.(*workerPool).Start.func2()
	/home/dev/go/pkg/mod/github.com/valyala/fasthttp@v1.28.0/workerpool.go:66 +0x56
created by github.com/valyala/fasthttp.(*workerPool).Start
	/home/dev/go/pkg/mod/github.com/valyala/fasthttp@v1.28.0/workerpool.go:58 +0xd9

goroutine 38 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/google/gopacket.(*PacketSource).Packets
	/home/dev/go/pkg/mod/github.com/google/gopacket@v1.1.19/packet.go:861 +0x96

goroutine 53 [select]:
project.io/project/networking/network.ReadArpPackets(0x0, {0x2, 0x5dc, {0xc0004c7c70, 0x5}, {0xc0004c7c76, 0x6, 0x6}, 0x13}, 0xc00021c2a0, ...)
	/home/dev/dev/project-project-wails/networking/network/arp.go:76 +0x14f
created by project.io/project/networking/scan.sss
	/home/dev/dev/project-project-wails/networking/scan/scan.go:41 +0x1d5

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x7f7b2dd39628, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0000ac700?, 0xc000720000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0000ac700, {0xc000720000, 0xf2f, 0xf2f})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0000ac700, {0xc000720000?, 0xc000295ce0?, 0xc000720716?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00028e370, {0xc000720000?, 0x9c0?, 0xc000295ce0?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000382078, {0xc000720000?, 0x0?, 0x1ad8800?})
	/usr/local/go/src/crypto/tls/conn.go:784 +0x3d
bytes.(*Buffer).ReadFrom(0xc0001f8278, {0x1606f00, 0xc000382078})
	/usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0001f8000, {0x1607aa0?, 0xc00028e370}, 0x81e?)
	/usr/local/go/src/crypto/tls/conn.go:806 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0001f8000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:613 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:581
crypto/tls.(*Conn).Read(0xc0001f8000, {0xc000378000, 0x1000, 0x7499e0?})
	/usr/local/go/src/crypto/tls/conn.go:1284 +0x16f
bufio.(*Reader).Read(0xc000359980, {0xc00033dd20, 0x9, 0x757de2?})
	/usr/local/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x1606d60, 0xc000359980}, {0xc00033dd20, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:350
net/http.http2readFrameHeader({0xc00033dd20?, 0x9?, 0xc0001f41e0?}, {0x1606d60?, 0xc000359980?})
	/usr/local/go/src/net/http/h2_bundle.go:1566 +0x6e
net/http.(*http2Framer).ReadFrame(0xc00033dce0)
	/usr/local/go/src/net/http/h2_bundle.go:1830 +0x95
net/http.(*http2clientConnReadLoop).run(0xc0000b3f98)
	/usr/local/go/src/net/http/h2_bundle.go:8815 +0x130
net/http.(*http2ClientConn).readLoop(0xc0001ea180)
	/usr/local/go/src/net/http/h2_bundle.go:8711 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7439 +0xa65

goroutine 51 [select]:
net/http.(*http2ClientConn).RoundTrip(0xc0001ea180, 0xc000262500)
	/usr/local/go/src/net/http/h2_bundle.go:7869 +0x451
net/http.(*http2Transport).RoundTripOpt(0xc0000ac080, 0xc000262500, {0xe0?})
	/usr/local/go/src/net/http/h2_bundle.go:7213 +0x1b7
net/http.(*http2Transport).RoundTrip(...)
	/usr/local/go/src/net/http/h2_bundle.go:7174
net/http.http2noDialH2RoundTripper.RoundTrip({0x1971720?}, 0xc000262500?)
	/usr/local/go/src/net/http/h2_bundle.go:9677 +0x1b
net/http.(*Transport).roundTrip(0x1971720, 0xc000262500)
	/usr/local/go/src/net/http/transport.go:539 +0x390
net/http.(*Transport).RoundTrip(0x415265?, 0x1607b40?)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc000262500, {0x1607b40, 0x1971720}, {0xa11da0?, 0x1?, 0x0?})
	/usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc000591830, 0xc000262500, {0xc0000599f8?, 0x41f0b3?, 0x0?})
	/usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc000591830, 0xc000262500)
	/usr/local/go/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:593
project.io/project/networking/remote.DoAuthenticatedGetRequest({0xc0000d3248, 0x17}, {0xc0003c00b0, 0xa1})
	/home/dev/dev/project-project-wails/networking/remote/api.go:23 +0x2e5
project.io/project/networking/remote.GetIPs({{0xc0004c7ca0, 0x10, 0x10}, {0xc0004c7c88, 0x4, 0x6}}, {0xc0003c00b0, 0xa1})
	/home/dev/dev/project-project-wails/networking/remote/api.go:69 +0xeb
project.io/project/networking/scan.sss(0x0, {0x2, 0x5dc, {0xc0004c7c70, 0x5}, {0xc0004c7c76, 0x6, 0x6}, 0x13}, {{0xc0004c7ca0, ...}, ...}, ...)
	/home/dev/dev/project-project-wails/networking/scan/scan.go:44 +0x21a
created by main.(*App).Scan
	/home/dev/dev/project-project-wails/app.go:212 +0x5dd

goroutine 52 [select]:
main.(*App).Scan.func1(0xc00021c1e0, 0x0?, 0x0?)
	/home/dev/dev/project-project-wails/app.go:217 +0xf4
created by main.(*App).Scan
	/home/dev/dev/project-project-wails/app.go:215 +0x6ca

goroutine 54 [runnable]:
syscall.Syscall(0x1, 0x3, 0xc00076c5b0, 0xcd)
	/usr/local/go/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.write(0xc0000ac700?, {0xc00076c5b0?, 0x100?, 0x0?})
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:924 +0x4d
syscall.Write(...)
	/usr/local/go/src/syscall/syscall_unix.go:216
internal/poll.ignoringEINTRIO(...)
	/usr/local/go/src/internal/poll/fd_unix.go:794
internal/poll.(*FD).Write(0xc0000ac700?, {0xc00076c5b0?, 0xcd?, 0xcd?})
	/usr/local/go/src/internal/poll/fd_unix.go:383 +0x36e
net.(*netFD).Write(0xc0000ac700, {0xc00076c5b0?, 0xbd?, 0xc0001f8228?})
	/usr/local/go/src/net/fd_posix.go:96 +0x29
net.(*conn).Write(0xc00028e370, {0xc00076c5b0?, 0x0?, 0xc000295d20?})
	/usr/local/go/src/net/net.go:195 +0x45
crypto/tls.(*Conn).write(0xc0001f8000, {0xc00076c5b0?, 0x5?, 0x5?})
	/usr/local/go/src/crypto/tls/conn.go:919 +0x108
crypto/tls.(*Conn).writeRecordLocked(0xc0001f8000, 0x17, {0xc000721000, 0xb7, 0x1000})
	/usr/local/go/src/crypto/tls/conn.go:987 +0x351
crypto/tls.(*Conn).Write(0x452934?, {0xc000721000, 0xb7, 0x1000})
	/usr/local/go/src/crypto/tls/conn.go:1158 +0x3f4
net/http.http2stickyErrWriter.Write({{0x160e138?, 0xc0001f8000?}, 0xc0002bba40?, 0xc0001ea2b8?}, {0xc000721000, 0xb7, 0x1000})
	/usr/local/go/src/net/http/h2_bundle.go:7128 +0x149
bufio.(*Writer).Flush(0xc00025ef40)
	/usr/local/go/src/bufio/bufio.go:628 +0x62
net/http.(*http2ClientConn).writeHeaders(0xc0001ea180, 0x3, 0x1, 0xffffff, {0xc0001761c0?, 0x0?, 0x0?})
	/usr/local/go/src/net/http/h2_bundle.go:8209 +0x195
net/http.(*http2clientStream).encodeAndWriteHeaders(0xc0001ea300, 0xc000262500)
	/usr/local/go/src/net/http/h2_bundle.go:8093 +0x35e
net/http.(*http2clientStream).writeRequest(0xc0001ea300, 0xc000262500)
	/usr/local/go/src/net/http/h2_bundle.go:7981 +0x4a5
net/http.(*http2clientStream).doRequest(0x6?, 0xc0004c7c76?)
	/usr/local/go/src/net/http/h2_bundle.go:7899 +0x1e
created by net/http.(*http2ClientConn).RoundTrip
	/usr/local/go/src/net/http/h2_bundle.go:7828 +0x30a
^C
```
Here's my go env:
```GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dev/.cache/go-build"
GOENV="/home/dev/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dev/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dev/dev/netctrl-monitor-wails/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1189538100=/tmp/go-build -gno-record-gcc-switches"
```
And this is using gopacket v1.1.19.

**Comment by gardc** [comment]
It seems this issue was being caused by not having the correct privileges on the Go binary, and not a bug in gopacket.
